# Generated by Django 5.2.7 on 2025-10-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='pause_between_bookings',
            field=models.CharField(choices=[('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H')], default='0', help_text='How long to wait between bookings.', max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
