# Generated by Django 5.2.7 on 2025-10-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingsettings_pause_between_bookings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsettings',
            name='end_time',
            field=models.TimeField(verbose_name='End Time for available booking'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='pause_between_bookings',
            field=models.CharField(choices=[('0', '0M'), ('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H')], default='0', help_text='How long to wait between bookings.', max_length=3),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='period_of_each_booking',
            field=models.CharField(choices=[('0', '0M'), ('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H')], default='30', help_text='How long each booking take.', max_length=3),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time for available booking'),
        ),
    ]
