# Generated by Django 5.2.7 on 2025-10-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bookingsettings_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsettings',
            name='end_time',
            field=models.TimeField(help_text='End Time for available booking'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='start_time',
            field=models.TimeField(help_text='Start Time for available booking'),
        ),
    ]
