# Generated by Django 5.2.7 on 2025-11-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookingsettings_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingsettings',
            options={'verbose_name': 'Booking Settings', 'verbose_name_plural': 'Booking Settings'},
        ),
    ]
