# Generated by Django 5.2.7 on 2025-11-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookingservice_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingservice',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.bookingservice'),
        ),
    ]
