# Generated by Django 5.2.7 on 2025-11-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_bookingservice_booking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_service',
            new_name='service',
        ),
    ]
