# Generated by Django 5.2.7 on 2025-11-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_booking_service_booking_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAlertEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(blank=True, help_text='Email subject for booking alerts.', max_length=250, null=True)),
                ('email_header', models.CharField(blank=True, help_text='Email header for booking alerts.', max_length=250, null=True)),
                ('email_body', models.TextField(blank=True, help_text='Email template for booking alerts.', null=True)),
                ('booking_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_emails', to='booking.bookingservice')),
            ],
        ),
        migrations.CreateModel(
            name='BookingAlertSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_body', models.TextField(blank=True, help_text='SMS template for booking alerts.', null=True)),
                ('booking_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_sms', to='booking.bookingservice')),
            ],
        ),
    ]
