# Generated by Django 5.2.7 on 2025-11-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_bookingalertemail_bookingalertsms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingalertemail',
            name='booking_service',
        ),
        migrations.RemoveField(
            model_name='bookingalertsms',
            name='booking_service',
        ),
        migrations.AddField(
            model_name='bookingalertemail',
            name='booking_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_emails', to='booking.bookingsettings'),
        ),
        migrations.AddField(
            model_name='bookingalertsms',
            name='booking_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_sms', to='booking.bookingsettings'),
        ),
    ]
