# Generated by Django 5.2.7 on 2025-11-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_bookingalertemail_booking_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alerts',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.bookingalertemail'),
        ),
    ]
