# Generated by Django 5.2.7 on 2025-11-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_alerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='alerts',
        ),
        migrations.AddField(
            model_name='booking',
            name='email_alerts',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookings', to='booking.bookingalertemail'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sms_alerts',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookings', to='booking.bookingalertsms'),
        ),
    ]
