# Generated by Django 5.2.7 on 2025-11-04 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_booking_alerts_booking_email_alerts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email_alerts',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sms_alerts',
        ),
        migrations.AddField(
            model_name='booking',
            name='email_alerts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.bookingalertemail'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sms_alerts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.bookingalertsms'),
        ),
    ]
