# Generated by Django 5.2.7 on 2025-11-04 14:11

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_booking_email_alerts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email_alerts',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.bookingalertemail'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sms_alerts',
            field=models.ForeignKey(blank=True, default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.bookingalertsms'),
        ),
        migrations.AlterField(
            model_name='bookingalertemail',
            name='email_body',
            field=models.TextField(blank=True, default='Dear {{booking.user_name}},\n\nYour booking for {{booking.service.name}} on \n                        {{booking.date}} at {{booking.time}} has been approved.\n\nThank you!', help_text='Email template for booking alerts.', null=True),
        ),
    ]
