# Generated by Django 5.2.7 on 2025-11-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCalendarSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable or disable Google Calendar synchronization.')),
                ('calendar_id', models.CharField(blank=True, help_text='Google Calendar ID to sync with.', max_length=255)),
                ('last_synced', models.DateTimeField(blank=True, help_text='Timestamp of the last synchronization.', null=True)),
            ],
        ),
    ]
