# Generated by Django 5.2.7 on 2025-11-01 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcalendar_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcalendarsyncsettings',
            options={'verbose_name': 'Google Calendar Sync Settings', 'verbose_name_plural': 'Google Calendar Sync Settings'},
        ),
        migrations.CreateModel(
            name='GCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Unique ID of the Google Calendar event.', max_length=255, unique=True)),
                ('summary', models.CharField(help_text='Summary or title of the event.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event.')),
                ('start_time', models.DateTimeField(help_text='Start time of the event.')),
                ('end_time', models.DateTimeField(help_text='End time of the event.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the event was created in the system.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the event was last updated in the system.')),
                ('sync_settings', models.ForeignKey(help_text='The Google Calendar sync settings this event is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gcalendar_sync.gcalendarsyncsettings')),
            ],
            options={
                'verbose_name': 'Google Calendar Event',
                'verbose_name_plural': 'Google Calendar Events',
            },
        ),
        migrations.CreateModel(
            name='GCalendarReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'Email'), ('popup', 'Popup')], help_text='Method of the reminder', max_length=50)),
                ('minutes_before', models.IntegerField(help_text='Number of minutes before the event when the reminder should trigger.')),
                ('event', models.ForeignKey(help_text='The Google Calendar sync settings this reminder is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='gcalendar_sync.gcalendarsyncsettings')),
            ],
            options={
                'verbose_name': 'Google Calendar Reminder',
                'verbose_name_plural': 'Google Calendar Reminders',
            },
        ),
    ]
