# Generated by Django 5.2.7 on 2025-11-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_bookingsettings_options'),
        ('gcalendar_sync', '0002_alter_gcalendarsyncsettings_options_gcalendarevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcalendarevent',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='The booking this event is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gcalendar_events', to='booking.booking'),
        ),
    ]
