# Generated by Django 5.2.7 on 2025-11-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcalendar_sync', '0003_gcalendarevent_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcalendarsyncsettings',
            options={'verbose_name': 'Calendar Sync Settings', 'verbose_name_plural': 'Calendar Sync Settings'},
        ),
    ]
