# Generated by Django 5.2.7 on 2025-11-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcalendar_sync', '0004_alter_gcalendarsyncsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcalendarsyncsettings',
            name='calendar_id',
            field=models.CharField(blank=True, help_text="Google Calendar ID to sync with. ( use 'primary' for main calendar )", max_length=255),
        ),
    ]
