# Generated by Django 5.2.7 on 2025-11-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcalendar_sync', '0005_alter_gcalendarsyncsettings_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcalendarsyncsettings',
            name='calendar_id',
            field=models.CharField(default='primary', help_text="Google Calendar ID to sync with. ( use 'primary' for main calendar )", max_length=255),
        ),
        migrations.AlterField(
            model_name='gcalendarsyncsettings',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable Google Calendar synchronization.'),
        ),
    ]
